.PHONY: all clean run pack build-pre build-post

all: build-pre run build-post	
	
build-post: 

run: 
	@cd verify && ./run_all.sh ../main.js

pack:
	zip -r semantic.zip verify/ Makefile.checker\
		README.md 

clean:
	rm -rf verify/output/
